# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_unclassFactor <- function(x) {
    .Call(`_fplot_cpp_unclassFactor`, x)
}

cpp_unik <- function(x_sorted, k_max) {
    .Call(`_fplot_cpp_unik`, x_sorted, k_max)
}

cpp_string_shorten <- function(x, max_size = 15L) {
    .Call(`_fplot_cpp_string_shorten`, x, max_size)
}

